# golangci-lint configuration (v1)
# https://golangci-lint.run/docs/configuration/

run:
  timeout: 2m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  print-issued-lines: true
  print-linter-name: true
